export const SAVE_RECIPES_LIST = 'home/SAVE_RECIPES_LIST';
export const SAVE_LEFT_DATA = 'home/SAVE_LEFT_DATA';
export const SAVE_RIGHT_DATA = 'home/SAVE_RIGHT_DATA';

export const SAVE_DYNAMIC_LIST = 'home/SAVE_DYNAMIC_LIST';
export const SAVE_LEFT_DYNAMIC = 'home/SAVE_LEFT_DYNAMIC';
export const SAVE_RIGHT_DYNAMIC = 'home/SAVE_RIGHT_DYNAMIC';

export const CLEAR_HOME_REDUX_DATA = 'home/CLEAR_HOME_REDUX_DATA';
