export const SAVE_SELECTED_TAB = 'tab/SAVE_SELECTED_TAB';
export const SAVE_UNREAD_NUMBER = 'tab/SAVE_UNREAD_NUMBER';
export const SAVE_UNREAD_COLLECT_NUMBER = 'tab/SAVE_UNREAD_COLLECT_NUMBER';
export const SAVE_UNREAD_COMMENT_NUMBER = 'tab/SAVE_UNREAD_COMMENT_NUMBER';
export const SAVE_UNREAD_FAN_NUMBER = 'tab/SAVE_UNREAD_FAN_NUMBER';
export const SAVE_UNREAD_LIKE_NUMBER = 'tab/SAVE_UNREAD_LIKE_NUMBER';
